# Generated by Django 3.0.3 on 2020-03-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(max_length=100, null=True)),
                ('subcategory', models.CharField(max_length=100, null=True)),
                ('blog', models.CharField(max_length=1000, null=True)),
                ('blog_img', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
