# Generated by Django 3.0.3 on 2020-03-25 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200325_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='blog_category',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='subcategory',
            new_name='blog_title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
