# Generated by Django 3.0.3 on 2020-03-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200303_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
