# Generated by Django 3.0.3 on 2020-03-04 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_auto_20200303_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='adlist',
            name='ad_img',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='adlist',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 4, 17, 27, 51, 380411)),
        ),
    ]
