# Generated by Django 3.0.3 on 2020-03-05 03:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_auto_20200304_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adlist',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 5, 3, 26, 55, 372754)),
        ),
    ]
