# Generated by Django 3.0.3 on 2020-03-07 07:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_auto_20200305_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='adlist',
            name='ad_img2',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='adlist',
            name='ad_img3',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='adlist',
            name='ad_img4',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='adlist',
            name='ad_img5',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='adlist',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 7, 7, 26, 46, 211285)),
        ),
    ]
