# Generated by Django 3.0.3 on 2020-03-08 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_auto_20200307_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='adlist',
            name='ad_rating',
            field=models.IntegerField(default=0, max_length=5),
        ),
        migrations.AddField(
            model_name='adlist',
            name='buyer_email',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='adlist',
            name='buyer_name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='adlist',
            name='review',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='adlist',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 8, 13, 25, 41, 394055)),
        ),
    ]
