# Generated by Django 3.0.3 on 2020-03-09 06:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_auto_20200309_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adlist',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 9, 6, 54, 23, 277258, tzinfo=utc)),
        ),
    ]
