# Generated by Django 3.0.3 on 2020-03-09 12:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0012_auto_20200309_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adlist',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='adlist',
            name='post_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
