# Generated by Django 3.0.3 on 2020-03-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0013_auto_20200309_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='adlist',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='adlist',
            name='payment_method',
            field=models.CharField(default='CARD', max_length=100),
        ),
    ]
