# Generated by Django 3.0.3 on 2020-03-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0015_auto_20200309_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='adlist',
            name='term_conditions',
            field=models.BooleanField(default=False),
        ),
    ]
