# Generated by Django 3.0.3 on 2020-03-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0016_adlist_term_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='adlist',
            name='subcategory',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
