# Generated by Django 3.0.4 on 2020-03-28 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0017_adlist_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='adlist',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
