# Generated by Django 3.0.3 on 2020-03-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='data_value',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
