# Generated by Django 3.0.3 on 2020-03-09 04:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.IntegerField(default=0, max_length=100)),
                ('seller_email', models.CharField(max_length=100, null=True)),
                ('item_price', models.FloatField()),
                ('buyer_name', models.CharField(max_length=1000, null=True)),
                ('buyer_email', models.CharField(max_length=1000, null=True)),
                ('review', models.CharField(max_length=1000, null=True)),
                ('ad_rating', models.IntegerField(default=0, max_length=5)),
                ('paid', models.BooleanField(default=False)),
                ('post_date', models.DateTimeField(default=datetime.datetime(2020, 3, 9, 4, 12, 55, 484926))),
                ('payment_method', models.CharField(max_length=100)),
            ],
        ),
    ]
