# Generated by Django 3.0.3 on 2020-03-09 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20200309_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='payment_method',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
