# Generated by Django 3.0.3 on 2020-03-09 11:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20200309_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 9, 11, 54, 38, 305135, tzinfo=utc)),
        ),
    ]
