# Generated by Django 3.0.3 on 2020-03-09 13:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_auto_20200309_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 9, 12, 59, 59, 845299, tzinfo=utc)),
        ),
    ]
