# Generated by Django 3.0.3 on 2020-03-11 15:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_auto_20200309_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='post_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
